### ISSUE TITLE
PopulateDB - Admin table needs to be added to the database

### ISSUE THREAD

**Issue by cbarrieau232** [cbshashank/swegroup-4#22]
We need to add in the AdminTb table to the database, with two fields:  username nchar(10) and password nchar(10)

It should have "Admin", "Admin" as the only entry.

**Comment by sag129** [comment]
Works just like the question ans table.  Derives admin info from csv file.  Helps reuse code.

**Comment by sag129** [comment]
done this way: username varchar(20) and password varchar(30)

**Comment by sag129** [comment]
needs to be tested along with Shashank's new code.
