### ISSUE TITLE
owl-front - Pictures are of variant size

### ISSUE THREAD

**Issue by cbarrieau232** [cbshashank/swegroup-4#26]
See attached picture - the images associated with categories are variant size.
![icon_size](https://cloud.githubusercontent.com/assets/14844945/11414305/d3836cfa-93c1-11e5-832d-7fde03449a3d.png)

**Comment by sag129** [comment]
Does your QuestionView.js code have the following line?
<img width="927" alt="screen shot 2015-11-26 at 3 20 26 pm" src="https://cloud.githubusercontent.com/assets/12366059/11430232/7adccb42-9451-11e5-9c5d-e9cd9b720444.png">

**Comment by sag129** [comment]
This is what I see.
![what i see](https://cloud.githubusercontent.com/assets/12366059/11430455/e9c5490a-9454-11e5-822c-024d507a745a.png)

**Comment by cbarrieau232** [comment]
I do have that line but I still see the entries as very large.

**Comment by cbarrieau232** [comment]
I updated to the following code locally and this appears to work.  I can try a check-in to see if it breaks your version Wyliena?
            var img = document.createElement('img');
            img.src = url;
            img.alt = option;
            img.width=160;
        img.height=160;

**Comment by sag129** [comment]
I tried this code, too.  It works.  Feel free to make the change!
