### ISSUE TITLE
owl-front - Remove message boxes from clientcommunicationmodule.js

### ISSUE THREAD

**Issue by cbarrieau232** [cbshashank/swegroup-4#27]
Although useful for debugging, we need to remember to remove all the alert boxes from clientcommunicationmodule.js (should be one when categories are loaded).

**Comment by sag129** [comment]
Let's just comment them out rather than delete them.  I'll try that.

**Comment by sag129** [comment]
Made a commit to clientcommunicationmodule.js.  There's only 1 alert box I canceled out.  Let me know if you need any more changes.

**Comment by pitzer42** [comment]
Do you want to mark this issue as closed?

**Comment by cbarrieau232** [comment]
I did check this with latest synch - looks to be resolved.  Closing.
