### ISSUE TITLE
owl-front - update resultview.js - typo

### ISSUE THREAD

**Issue by cbarrieau232** [cbshashank/swegroup-4#28]
In resultview.js, GoogleimagesURL should be GoogleImageURL in order for the link to display properly.

**Comment by sag129** [comment]
I just reviewed resultview.js.  The change seems to be made.  Cannot find "GoogleimagesURL".  Can only find "GoogleImageURL"

**Comment by cbarrieau232** [comment]
Latest version I got has googleimagesURL.  Will update with a checkin.
