### ISSUE TITLE
OWLWebsite - Insert - an object with neither a name nor a plantid should not be added

### ISSUE THREAD

**Issue by cbarrieau232** [cbshashank/swegroup-4#29]
Insert - an object with neither a name nor a plantid should not be added.  Currently it is added in as a numeric.  This may be alright, but is different than what we said it would be.

**Comment by sag129** [comment]
Made a commit to populateDB program.cs code to make those two attributes NOT NULL.  Has to be tested.

**Comment by sag129** [comment]
the insert change actually needs to be made in OWLWebsite, in databasecomm.cs

**Comment by cbarrieau232** [comment]
Added code to return an error result if both name and plantid are null or an empty string.
