### ISSUE TITLE
SQL Test Query needs an update

### ISSUE THREAD

**Issue by cbarrieau232** [cbshashank/swegroup-4#3]
The order by statement in self_containing_code.sql needs to include the column for each section.

**Comment by cbarrieau232** [comment]
Example: 
select color_flower
from plant
group by color_flower
order by color_flower asc

**Comment by sag129** [comment]
-- this code is for making the controller code more self-containing
-- this code will find all of the values that the characteristics could take on
-- then we could list these values as question answer choices on the homepage

select color_flower
from plant
group by color_flower
order by asc;

select color_foliage
from plant
group by color_foliage
order by asc;

select color_fruit_seed
from plant
group by color_fruit_seed
order by asc;

select texture_foliage
from plant
group by texture_foliage
order by asc;

select shape
from plant
group by shape
order by asc;

select pattern
from plant
group by pattern
order by asc;

---

select us_state
from location
group by us_state
order by asc;

---

select type
from plant_type
group by type
order by asc;

**Comment by sag129** [comment]
just added these codes to the test query code.

**Comment by sag129** [comment]
I'll leave this issue open in case we need more test query codes.  do we?

**Comment by cbarrieau232** [comment]
I think you are okay to close it - it was really just about these queries.
