### ISSUE TITLE
owl-front - Result window - for large queries, system times out/takes a long time

### ISSUE THREAD

**Issue by cbarrieau232** [cbshashank/swegroup-4#30]
For searches which return many items, it takes a long time for the results window to display and it hangs, at least on my machine.

**Comment by cbarrieau232** [comment]
The issues appear to stem from the iframe.  To test I cludged together using command buttons instead and the system opens much, much quicker.  I think our solution may be to replace the iframes with some other means of loading the information (a button which launches a separate window was what I was thinking).

**Comment by sag129** [comment]
a potential nice fix to this is to use jquery's toggle.  http://www.w3schools.com/jquery/tryit.asp?filename=tryjquery_hide_show.  the results page could ideally show all of the plant names and their pictures, and then when you think you have the right plant, you can click on the plant name or picture (either is fine, maybe picture) and underneath the picture, you'll see an iframe loading up and showing you related images/weblinks.  this way, you don't have to command click/open a weblink in another browser and this way you can still manage performance and bring down run time.

**Comment by sag129** [comment]
@pitzer42 this is a big issue, please let us know if you need help

**Comment by sag129** [comment]
ONE IDEA - create a common iframe -- two iFrames, update the iframe depending on the result plant clicked upon.

**Comment by sag129** [comment]
Along with iFrame, show a number of how many results are yielded (array.Length) and a message to say "narrow your search".

**Comment by cbarrieau232** [comment]
Checked outside of IIS.  Buttons load promptly and display the duckduckgo results as tabs.

**Comment by cbarrieau232** [comment]
Looks good.  Tested links on demo pc and it works.  Closing.
