### ISSUE TITLE
OWLWebsite - For null or empty images, we need a default image

### ISSUE THREAD

**Issue by cbarrieau232** [cbshashank/swegroup-4#38]
We need to 1) decide on a default image and 2)have this image assigned to any object which has a null value.

The assignment can be done in the query when we are creating the FloraObjects.  We just need to settle on an image.

**Comment by sag129** [comment]
I volunteer "./pictures/cherry_blossom.png".  It's my go-to image during the mock-ups.  It looks pretty.  There is also "./pictures/owl_library_small.png".  It has a smaller width/height dimensions.  To standardize things, the dimensions should be 160px x 160px

**Comment by sag129** [comment]
for images,
alt = "[can only equal text but not image links]"

**Comment by sag129** [comment]
when backend returns string NULL (it is string NULL), then show a certain default picture

**Comment by cbarrieau232** [comment]
Updated to display owl.jpg currently.  We can change to whatever, but that one loads quick (and the owl is cute).
