### ISSUE TITLE
CreateDB - References to ConsoleApplication1 causes project not to load

### ISSUE THREAD

**Issue by cbarrieau232** [cbshashank/swegroup-4#4]
The project CreateDB references ConsoleApplication1 in the solution.  This causes the project to not load.

**Comment by sag129** [comment]
The original name was "ConsoleApplication1", but I changed it to createDB.  I thought that the references would change, too.

**Comment by sag129** [comment]
Made a new commit.  See how you like it now.

**Comment by cbarrieau232** [comment]
I did need to make a tweak - the issue is in the solution file (.sln).  It should be corrected now.
