### ISSUE TITLE
owl-front - reset button not working

### ISSUE THREAD

**Issue by cbarrieau232** [cbshashank/swegroup-4#41]
In testing at the backend, the reset button does not appear to be clearing out prior selections.  The code to handle the button may have been lost in a merge, and needs to be re-implemented.

**Comment by pitzer42** [comment]
I will take a look at it

**Comment by sag129** [comment]
I tested it tonight.  It works.

**Comment by cbarrieau232** [comment]
Tested with my revision and does not appear to be working - 
If you look in c:\OWL_log.txt (from later revision of managed c# code), it logs the json sent to the server.
If you click on an option (leafcolor red) then go to the log file, you should see an entry timestamped for that query

Click reset, then go to a different option (flowercolor) and click on an entry.  

When you go back to the log file, you will see (or I see here) that both leafcolor and flowercolor were sent.

**Comment by cbarrieau232** [comment]
Validated - reset works.
