### ISSUE TITLE
PopulateDB:  Gray-green vs grey-green causes no entries to return.

### ISSUE THREAD

**Issue by cbarrieau232** [cbshashank/swegroup-4#54]
The questionans column has a value of Grey-Green where the value in the database is Gray-Green.  This results in 0 returned entries for Grey-Green.  We should just change the spelling to match in the questionans table (change to Gray-Green). (not a huge deal if we don't get it done, just logging it).

**Comment by cbshashank** [comment]
Fixed see commit fbbd47e

**Comment by cbarrieau232** [comment]
Verified defect fixed (needed to update csv in bin file).  Gray-Green now returns results.  Closing.
