### ISSUE TITLE
Query not return anything with new owl.html

### ISSUE THREAD

**Issue by cbarrieau232** [cbshashank/swegroup-4#6]
Selecting options does not send them to the web server - it is currently receiving an empty configuration (at least on my setup).  We just need to investigate.

**Comment by cbarrieau232** [comment]
Partially fixed - need to update the location drop down, then should be all set.

**Comment by sag129** [comment]
how do you want the location drop down to be altered?

**Comment by cbarrieau232** [comment]
It needs to ultimately update the answer variable in AbstractQuestionWidget

**Comment by cbarrieau232** [comment]
Updated code.  Added an id to dropdown (since it is the only one currently) and GetAnswers() checks the value in it and sends it to the communication module.  Will close for now.
