### ISSUE TITLE
Images not displaying properly

### ISSUE THREAD

**Issue by cbarrieau232** [cbshashank/swegroup-4#7]
Images currently do not display properly in the window - image urls are failing to be displays for all the plants, including ones which have valid links

**Comment by sag129** [comment]
What kind of image urls? Category ones or results?

**Comment by cbarrieau232** [comment]
Results.  There should be some which display with the current URL model but they are not working.

**Comment by cbarrieau232** [comment]
Updated Results code.  This now displays properly in testing with test images returned by C# server.
