### ISSUE TITLE
Questions do not display with latest build

### ISSUE THREAD

**Issue by cbarrieau232** [cbshashank/swegroup-4#9]
Questions do not display with latest build on the front end, even using modifications to show test data.

**Comment by cbarrieau232** [comment]
Issue was a comparison of an array against a value of 0 (empty).  Added to check the array .length and it works (see below)

  if (questions[i].options.length > 0) {
                    var widget = widgetFactory(questions[i]);
                    questionContainer.appendChild(widget.asHTML());
                    widgets.push(widget);
                }

**Comment by sag129** [comment]
I still can't see the images on the front-end.  I am working on this.

**Comment by sag129** [comment]
Latest commit fixed the .jpg files.  File format issues were the problem between jpeg and jpg.  We want jpg.
